"""

Revision ID: 67b49f9cf5af
Revises: 7f67ae9a7c54
Create Date: 2026-07-07 19:55:25.472819

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "67b49f9cf5af"
down_revision: str | Sequence[str] | None = "7f67ae9a7c54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
